version: '3.8'

services:
  npmbadge:
    image: ghcr.io/lucascorpion/npmbadge.com:latest
    networks:
      - default
      - ssl
    deploy:
      labels:
        - hostname=npmbadge.com
        - traefik.http.services.npmbadge.loadbalancer.server.port=3000

networks:
  default:
  ssl:
    external: true
    name: ssl
