name: Deploy

on:
  registry_package:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deployment script
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_KEY" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -H 'npmbadge.com' > "$HOME/.ssh/known_hosts"
          docker stack deploy --with-registry-auth --resolve-image always --prune --compose-file ./production-stack.yml 'npmbadge'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DOCKER_HOST: 'ssh://azureuser@npmbadge.com'
