name: Publish

on:
  release:
    types: [published]
  push:
    branches: [set-up-ci]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/LucaScorpion/npm-badge-generator:${{ github.ref }}
            ghcr.io/LucaScorpion/npm-badge-generator:latest
